// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"
	"time"

	"server/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/list-voices/:platform",
				Handler: ListVoicesHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/text-to-speech",
				Handler: TextToSpeechHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
		rest.WithTimeout(10000*time.Millisecond),
	)
}
